spring:
  application:
    name: transaction-autorization-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    aws:
      sqs:
        region: ${AWS_REGION}
        endpoint: ${AWS_SQS_ENDPOINT}
        listener:
          max-concurrent-messages: 10
          max-messages-per-poll: 10
          poll-timeout: 10

      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}

aws:
  sqs:
    queue-name: ${AWS_SQS_QUEUE_NAME}
